In [7]:
import torch.nn as nn
import torch

In [78]:
l = nn.ConvTranspose2d(4,16,3, padding=0) 

In [66]:
l

ConvTranspose2d(4, 16, kernel_size=(3, 3), stride=(1, 1), padding=(5, 5))

In [67]:
d= torch.randn(1,4,2,2)
d

tensor([[[[ 0.0831, -1.4782],
          [-0.4602, -0.4582]],

         [[-1.2727, -0.3764],
          [-0.6034,  0.0823]],

         [[ 0.0666, -1.6122],
          [-0.4420, -0.5475]],

         [[ 0.2697,  0.4773],
          [-0.0847, -0.8418]]]])

In [68]:
d1 = torch.diag(torch.randn(4))
d1

tensor([[ 0.9116,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.5576,  0.0000,  0.0000],
        [ 0.0000,  0.0000, -0.2780,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  2.6383]])

In [73]:
i = [d1.numpy() for i in range(4)]

In [74]:
i = torch.tensor(i).unsqueeze(0)

In [75]:
i.shape

torch.Size([1, 4, 4, 4])

In [79]:
i

tensor([[[[ 0.9116,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.5576,  0.0000,  0.0000],
          [ 0.0000,  0.0000, -0.2780,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  2.6383]],

         [[ 0.9116,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.5576,  0.0000,  0.0000],
          [ 0.0000,  0.0000, -0.2780,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  2.6383]],

         [[ 0.9116,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.5576,  0.0000,  0.0000],
          [ 0.0000,  0.0000, -0.2780,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  2.6383]],

         [[ 0.9116,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.5576,  0.0000,  0.0000],
          [ 0.0000,  0.0000, -0.2780,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  2.6383]]]])

In [82]:
nn.ConvTranspose2d(4,16,3, padding=0)(i)

tensor([[[[ 4.2096e-02, -4.5081e-02, -1.5021e-01, -2.0091e-02, -2.0091e-02,
           -2.0091e-02],
          [-1.3851e-01,  3.2456e-02, -1.6248e-01, -9.9680e-02, -2.0091e-02,
           -2.0091e-02],
          [ 4.6936e-03,  1.1068e-02, -3.4499e-02, -9.0220e-02,  1.9584e-02,
           -2.0091e-02],
          [-2.0091e-02, -4.9309e-03,  7.9384e-02,  1.5281e-01, -5.3652e-02,
           -3.9664e-01],
          [-2.0091e-02, -2.0091e-02, -2.7649e-02, -3.9438e-01,  2.3214e-02,
           -3.8794e-01],
          [-2.0091e-02, -2.0091e-02, -2.0091e-02,  5.1635e-02,  2.7971e-01,
           -3.2593e-02]],

         [[ 1.0101e-01,  1.5781e-01,  2.5399e-02,  7.8473e-02,  7.8473e-02,
            7.8473e-02],
          [-1.2318e-01, -1.2548e-02,  1.2441e-02,  4.6008e-02,  7.8473e-02,
            7.8473e-02],
          [ 5.2280e-02, -4.9001e-02, -5.3597e-02, -1.5793e-02,  9.4656e-02,
            7.8473e-02],
          [ 7.8473e-02,  6.2451e-02,  1.3744e-01,  1.3827e-01,  3.4300e-01,
           -7

In [88]:
nn.ConvTranspose2d(4,16,3, padding=0)(i).shape

torch.Size([1, 16, 6, 6])

In [48]:
l(d).size()

torch.Size([1, 16, 2, 2])

In [35]:
a = list(range(10))

In [36]:
sorted(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]