In [1]:
import tensorflow as tf 
import tensorflow_datasets as tfds
from tensorflow.keras import layers, models, optimizers, losses, metrics
import tensorboard

In [9]:
%load_ext tensorboard

In [2]:
# generate a random tensor of size 3x3

def get_data(sz = 4):
    x =  tf.random.normal((sz,3))
    y = tf.random.normal((sz,1))
    return (x,y)

In [3]:
get_data()

(<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[-0.12771428,  0.06715772, -0.5954443 ],
        [-0.6053379 , -3.487289  , -0.28666818],
        [-0.9452204 ,  0.25525218, -1.3282195 ],
        [-0.06579804, -1.7529793 , -1.6900126 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[-1.700986  ],
        [-0.9078052 ],
        [ 0.10713813],
        [ 0.15433644]], dtype=float32)>)

In [4]:
# tensorboard callback to log the loss and weights

tfb = tf.keras.callbacks.TensorBoard(log_dir = 'logs')


In [5]:
tf_model = tf.keras.Sequential([
    layers.Input(shape=(3,)),
    layers.Dense(2, activation='relu'),
])

tf_model.compile(optimizer='adam', loss='mse', metrics=['mse'])
    

In [6]:
x, y = get_data(100)

In [7]:
tf_model.fit(x, y, epochs=100)

Epoch 1/100
4/4 [==============================] - 3s 4ms/step - loss: 1.9373 - mse: 1.9373
Epoch 2/100
4/4 [==============================] - 0s 5ms/step - loss: 1.9266 - mse: 1.9266
Epoch 3/100
4/4 [==============================] - 0s 5ms/step - loss: 1.9152 - mse: 1.9152
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 1.9049 - mse: 1.9049
Epoch 5/100
4/4 [==============================] - 0s 5ms/step - loss: 1.8954 - mse: 1.8954
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 1.8855 - mse: 1.8855
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 1.8757 - mse: 1.8757
Epoch 8/100
4/4 [==============================] - 0s 5ms/step - loss: 1.8655 - mse: 1.8655
Epoch 9/100
4/4 [==============================] - 0s 5ms/step - loss: 1.8548 - mse: 1.8548
Epoch 10/100
4/4 [==============================] - 0s 4ms/step - loss: 1.8456 - mse: 1.8456
Epoch 11/100
4/4 [==============================] - 0s 5ms/step - loss: 1.8348 

In [10]:
%tensorboard --logdir logs

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "C:\Users\vivek\anaconda3\envs\gpu\Scripts\tensorboard-script.py", line 9, in <module>
    sys.exit(run_main())
  File "C:\Users\vivek\anaconda3\envs\gpu\lib\site-packages\tensorboard\main.py", line 46, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "C:\Users\vivek\anaconda3\envs\gpu\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\vivek\anaconda3\envs\gpu\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\vivek\anaconda3\envs\gpu\lib\site-packages\tensorboard\program.py", line 276, in main
    return runner(self.flags) or 0
  File "C:\Users\vivek\anaconda3\envs\gpu\lib\site-packages\tensorboard\program.py", line 292, in _run_serve_subcommand
    server = self._make_server()
  File "C:\Users\vivek\anaconda3\envs\gpu\lib\site-packages\tensorboard\pr